## application settings
spring.application.name=sbwap

## datasource settings
spring.datasource.url=jdbc:h2:~/test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:dbinit/schema.sql 
spring.sql.init.data-locations=classpath:dbinit/data.sql 

## h2 settings
spring.h2.console.enabled=true

## MyBatis settings
mybatis.configuration.map-underscore-to-camel-case=true

## Log settings
logging.level.jp.co.pia.atlas.base_lib.mapper=DEBUG
logging.level.jp.co.pia.atlas.base_lib.mapper.custom=DEBUG
logging.level.jp.co.pia.atlas=DEBUG

## Message property settings
spring.messages.basename=msg/messages,msg/validation-messages

## Custom property settings
spring.config.import=custom.properties

## Mail settings
spring.mail.host=localhost
spring.mail.port=1025

## Redis session settings
#spring.session.redis.repository-type=indexed
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.password=

## SpringDoc
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
